In [1]:
import pandas as pd
data_europe = pd.read_csv("../data/gapminder_gdp_europe.csv",index_col='country')

In [3]:
data_europe

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720
Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510
Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740
Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400
France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700
Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420
Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440
Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350
Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111
Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320
Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280

In [4]:
data_europe.head()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820

In [5]:
data_europe.head(3)

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.00391,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.42230,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.97448,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080

In [6]:
data_europe.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,5661.057435,6963.012816,8365.486814,10143.823757,12479.575246,14283.979110,15617.896551,17214.310727,17061.568084,19076.781802,21711.732422,25054.481636
std,3114.060493,3677.950146,4199.193906,4724.983889,5509.691411,5874.464896,6453.234827,7482.957960,9109.804361,10065.457716,11197.355517,11800.339811
min,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
25%,3241.132406,4394.874315,5373.536612,6657.939047,9057.708094,10360.030300,11449.870115,12274.570680,8667.113214,9946.599306,11721.851483,14811.898210
50%,5142.469716,6066.721495,7515.733737,9366.067033,12326.379990,14225.754515,15322.824720,16215.485895,17550.155945,19596.498550,23674.863230,28054.065790
75%,7236.794919,9597.220820,10931.085348,13277.182058,16523.017127,19052.412163,20901.729730,23321.587723,25034.243045,27189.530312,30373.363307,33817.962533
max,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170

# Dataframe

In [8]:
type(data_europe)

pandas.core.frame.DataFrame

In [9]:
data_europe['gdpPercap_1952']

country
Albania                    1601.056136
Austria                    6137.076492
Belgium                    8343.105127
Bosnia and Herzegovina      973.533195
Bulgaria                   2444.286648
Croatia                    3119.236520
Czech Republic             6876.140250
Denmark                    9692.385245
Finland                    6424.519071
France                     7029.809327
Germany                    7144.114393
Greece                     3530.690067
Hungary                    5263.673816
Iceland                    7267.688428
Ireland                    5210.280328
Italy                      4931.404155
Montenegro                 2647.585601
Netherlands                8941.571858
Norway                    10095.421720
Poland                     4029.329699
Portugal                   3068.319867
Romania                    3144.613186
Serbia                     3581.459448
Slovak Republic            5074.659104
Slovenia                   4215.041741
Spain                      3834.034742
Sweden                     8527.844662
Switzerland               14734.232750
Turkey                     1969.100980
United Kingdom             9979.508487
Name: gdpPercap_1952, dtype: float64

In [10]:
type(data_europe['gdpPercap_1952'])

pandas.core.series.Series

In [ ]:
## extracting values
- by location
- by label

In [13]:
#by location
print(data_europe.iloc[0,1]) # 1st row, 2nd column

1942.284244

In [14]:
# by label
print(data_europe.loc['Albania','gdpPercap_1957'])

1942.284244

In [18]:
## Slicing
# select gdpPercap_1952 for Austria and Belgium
# by using iloc
data_europe.iloc[1,0]
data_europe.iloc[2,0]    # or 
data_europe.iloc[1:3,0]

country
Austria    6137.076492
Belgium    8343.105127
Name: gdpPercap_1952, dtype: float64

In [16]:
# by using loc
data_europe.loc['Austria':'Belgium','gdpPercap_1952']

country
Austria    6137.076492
Belgium    8343.105127
Name: gdpPercap_1952, dtype: float64

In [20]:
print(data_europe.iloc[1:3,0].max())

8343.105127

In [21]:
print(data_europe.iloc[1:3,0].mean())

7240.0908095

In [22]:
# mutiple slicing
data_europe.iloc[1:3,0:2]

         gdpPercap_1952  gdpPercap_1957
country
Austria     6137.076492     8842.598030
Belgium     8343.105127     9714.960623

In [ ]:
#help(data.mean)
# data.mean(axis=1)
# data.T.mean()

# selecting values by comparison(filtering)

In [23]:
subset = data_europe.loc['Italy':'Poland','gdpPercap_1962':'gdpPercap_1972']

In [24]:
subset

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy           8243.582340    10022.401310    12269.273780
Montenegro      4649.593785     5907.850937     7778.414017
Netherlands    12790.849560    15363.251360    18794.745670
Norway         13450.401510    16361.876470    18965.055510
Poland          5338.752143     6557.152776     8006.506993

In [25]:
subset>10000

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy                 False            True            True
Montenegro            False           False           False
Netherlands            True            True            True
Norway                 True            True            True
Poland                False           False           False

In [26]:
mask = subset > 10000
subset[mask]

             gdpPercap_1962  gdpPercap_1967  gdpPercap_1972
country
Italy                   NaN     10022.40131     12269.27378
Montenegro              NaN             NaN             NaN
Netherlands     12790.84956     15363.25136     18794.74567
Norway          13450.40151     16361.87647     18965.05551
Poland                  NaN             NaN             NaN

In [27]:
subset[mask].mean()

gdpPercap_1962    13120.625535
gdpPercap_1967    13915.843047
gdpPercap_1972    16676.358320
dtype: float64

In [28]:
subset.mean()

gdpPercap_1962     8894.635868
gdpPercap_1967    10842.506571
gdpPercap_1972    13162.799194
dtype: float64

# Group

In [31]:
# creat a new column
data_europe['gdp_high_1962'] = data_europe['gdpPercap_1962'] > data_europe['gdpPercap_1962'].mean()

In [32]:
data_europe

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007,gdp_high_1962
country,,,,,,,,,,,,,
Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526,False
Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700,True
Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080,True
Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803,False
Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820,False
Croatia,3119.236520,4338.231617,5477.890018,6960.297861,9164.090127,11305.385170,13221.821840,13822.583940,8447.794873,9875.604515,11628.388950,14619.222720,False
Czech Republic,6876.140250,8256.343918,10136.867130,11399.444890,13108.453600,14800.160620,15377.228550,16310.443400,14297.021220,16048.514240,17596.210220,22833.308510,True
Denmark,9692.385245,11099.659350,13583.313510,15937.211230,18866.207210,20422.901500,21688.040480,25116.175810,26406.739850,29804.345670,32166.500060,35278.418740,True
Finland,6424.519071,7545.415386,9371.842561,10921.636260,14358.875900,15605.422830,18533.157610,21141.012230,20647.164990,23723.950200,28204.590570,33207.084400,True
France,7029.809327,8662.834898,10560.485530,12999.917660,16107.191710,18292.635140,20293.897460,22066.442140,24703.796150,25889.784870,28926.032340,30470.016700,True
Germany,7144.114393,10187.826650,12902.462910,14745.625610,18016.180270,20512.921230,22031.532740,24639.185660,26505.303170,27788.884160,30035.801980,32170.374420,True
Greece,3530.690067,4916.299889,6017.190733,8513.097016,12724.829570,14195.524280,15268.420890,16120.528390,17541.496340,18747.698140,22514.254800,27538.411880,False
Hungary,5263.673816,6040.180011,7550.359877,9326.644670,10168.656110,11674.837370,12545.990660,12986.479980,10535.628550,11712.776800,14843.935560,18008.944440,False
Iceland,7267.688428,9244.001412,10350.159060,13319.895680,15798.063620,19654.962470,23269.607500,26923.206280,25144.392010,28061.099660,31163.201960,36180.789190,True
Ireland,5210.280328,5599.077872,6631.597314,7655.568963,9530.772896,11150.981130,12618.321410,13872.866520,17558.815550,24521.947130,34077.049390,40675.996350,False
Italy,4931.404155,6248.656232,8243.582340,10022.401310,12269.273780,14255.984750,16537.483500,19207.234820,22013.644860,24675.024460,27968.098170,28569.719700,False
Montenegro,2647.585601,3682.259903,4649.593785,5907.850937,7778.414017,9595.929905,11222.587620,11732.510170,7003.339037,6465.613349,6557.194282,9253.896111,False
Netherlands,8941.571858,11276.193440,12790.849560,15363.251360,18794.745670,21209.059200,21399.460460,23651.323610,26790.949610,30246.130630,33724.757780,36797.933320,True
Norway,10095.421720,11653.973040,13450.401510,16361.876470,18965.055510,23311.349390,26298.635310,31540.974800,33965.661150,41283.164330,44683.975250,49357.190170,True
Poland,4029.329699,4734.253019,5338.752143,6557.152776,8006.506993,9508.141454,8451.531004,9082.351172,7738.881247,10159.583680,12002.239080,15389.924680,False
Portugal,3068.319867,3774.571743,4727.954889,6361.517993,9022.247417,10172.485720,11753.842910,13039.308760,16207.266630,17641.031560,19970.907870,20509.647770,False
Romania,3144.613186,3943.370225,4734.997586,6470.866545,8011.414402,9356.397240,9605.314053,9696.273295,6598.409903,7346.547557,7885.360081,10808.475610,False
Serbia,3581.459448,4981.090891,6289.629157,7991.707066,10522.067490,12980.669560,15181.092700,15870.878510,9325.068238,7914.320304,7236.075251,9786.534714,False
Slovak Republic,5074.659104,6093.262980,7481.107598,8412.902397,9674.167626,10922.664040,11348.545850,12037.267580,9498.467723,12126.230650,13638.778370,18678.314350,False
Slovenia,4215.041741,5862.276629,7402.303395,9405.489397,12383.486200,15277.030170,17866.721750,18678.534920,14214.716810,17161.107350,20660.019360,25768.257590,False
Spain,3834.034742,4564.802410,5693.843879,7993.512294,10638.751310,13236.921170,13926.169970,15764.983130,18603.064520,20445.298960,24835.471660,28821.063700,False
Sweden,8527.844662,9911.878226,12329.441920,15258.296970,17832.024640,18855.725210,20667.381250,23586.929270,23880.016830,25266.594990,29341.630930,33859.748350,True
Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,32135.323010,34480.957710,37506.419070,True
Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,6601.429915,6508.085718,8458.276384,False
United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,26074.531360,29478.999190,33203.261280,True

In [34]:
data_europe.groupby('gdp_high_1962')

In [35]:
data_europe.groupby('gdp_high_1962').mean()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
gdp_high_1962,,,,,,,,,,,,
False,3449.312073,4311.884225,5343.446065,6759.701045,8595.085921,10151.517643,11162.993296,11958.455717,10724.222667,12313.177273,14626.224897,17702.988656
True,8553.339832,10429.873281,12317.386256,14569.214995,17559.292057,19687.967181,21443.539270,24087.351893,25348.865938,27921.495416,30977.396110,34667.972456